"""add contact user

Revision ID: 388aff43b469
Revises: 8e19fee19545
Create Date: 2020-04-10 17:24:32.086111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '388aff43b469'
down_revision = '8e19fee19545'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('contact', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'contact')
    # ### end Alembic commands ###
