"""add order

Revision ID: 53d9723ebcbd
Revises: af209f1a6d29
Create Date: 2020-03-29 20:41:02.013107

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '53d9723ebcbd'
down_revision = 'af209f1a6d29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_date'), 'order', ['date'], unique=False)
    op.add_column('product', sa.Column('manufacturer_id', sa.Integer(), nullable=True))
    op.drop_constraint('product_ibfk_2', 'product', type_='foreignkey')
    op.create_foreign_key(None, 'product', 'manufacturer', ['manufacturer_id'], ['id'])
    op.drop_column('product', 'manufactorer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('manufactorer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.create_foreign_key('product_ibfk_2', 'product', 'manufacturer', ['manufactorer_id'], ['id'])
    op.drop_column('product', 'manufacturer_id')
    op.drop_index(op.f('ix_order_date'), table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###
