"""add roles and rangs for user and ambassador for manufacturer

Revision ID: 5a2000a54b6e
Revises: 20374d889a37
Create Date: 2020-04-05 16:51:25.748640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5a2000a54b6e'
down_revision = '20374d889a37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('manufacturer', sa.Column('ambassador', sa.String(length=64), nullable=False))
    op.alter_column('manufacturer', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=False)
    op.alter_column('product', 'manufacturer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('type', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=False)
    op.add_column('user', sa.Column('bank', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('rang', sa.Enum('Bronze', 'Silver', 'Gold', 'Platina', name='rangs'), nullable=True))
    op.add_column('user', sa.Column('role', sa.Enum('Reader', 'Admin', name='roles'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    op.drop_column('user', 'rang')
    op.drop_column('user', 'bank')
    op.alter_column('type', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=True)
    op.alter_column('product', 'manufacturer_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('manufacturer', 'name',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=64),
               nullable=True)
    op.drop_column('manufacturer', 'ambassador')
    # ### end Alembic commands ###
