"""add manufacturer

Revision ID: af209f1a6d29
Revises: ed2b2d41c3ca
Create Date: 2020-03-29 20:21:58.286849

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af209f1a6d29'
down_revision = 'ed2b2d41c3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('manufacturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturer_name'), 'manufacturer', ['name'], unique=False)
    op.add_column('product', sa.Column('manufactorer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'product', 'manufacturer', ['manufactorer_id'], ['id'])
    op.create_index(op.f('ix_type_name'), 'type', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_type_name'), table_name='type')
    op.drop_constraint(None, 'product', type_='foreignkey')
    op.drop_column('product', 'manufactorer_id')
    op.drop_index(op.f('ix_manufacturer_name'), table_name='manufacturer')
    op.drop_table('manufacturer')
    # ### end Alembic commands ###
